### ISSUE TITLE
Unclear why this library exists

### ISSUE THREAD

**Issue by curran** [gustavoguichard/string-ts#13]
The "the problem" section of the README is IMO not clear enough.

Suggested improvements:
 * Show the types you want to write that are not supported by TypeScript
 * Provide some real-world examples of use cases where you need more than the "string" type for transformed strings
 
 
 Here's the current state of the intro section of the README:
 
 ## 😬 The problem

When you are working with literal strings, the string manipulation functions only work at the runtime level and the types don't follow those transformations.
You end up losing type information and possibly having to cast the result.

```ts
const str = 'hello-world';
const result = str.replace('-', ' '); // you should use: as 'hello world'
//    ^? string
```

**Comment by BLamy** [comment]
`.replace` is a real world example. The native one will downcast any string literals to just string.

**Comment by jly36963** [comment]
Literals are more specific than `string` -- this library preserves literals (and unions of literals) after transformations, unlike most libraries.

## Example 1

Given the scenaro `camelCase('hello-world')`:
- Without string-ts (eg: lodash):  type is `string`
  - This is less specific
- With string-ts: type is `helloWorld`
  - This is precise

The point of this library is to _not_ lose specificity. Where a type can be more specific, it should be. 

## Example 2

Let's say I use `deepCamelKeys` to convert `process.env` to an object with camelCase keys.
Most implementations of `camelCase` would lose specificity, and the resulting type would look like this:

```ts
interface EnvLoose {
  [key: string]: string;
}

const env: EnvLoose = {
  someKey: "value",
};

// Typescript is okay with this, abc will be of type `string`
console.log(env.abc);
```

With `string-ts`, my type is kept precise. The output type would be something like:

```ts
interface EnvPrecise {
  nodeEnv: string;
}

const env2: EnvPrecise = {
  nodeEnv: "value",
};

// Property 'abc' does not exist on type 'EnvPrecise'
console.log(env2.abc);
```

**Comment by gustavoguichard** [comment]
@jly36963 , do you think we could improve the first section of the README to be somewhat similar to your answer here?
I'd love some PR helping me clarify that!
I'm also considering doing some sort of GIF like I did for [domain-functions](https://github.com/seasonedcc/domain-functions/#keep-your-business-logic-clean-with-domain-functions)

**Comment by curran** [comment]
Awesome ideas! I was thinking something even higher level than that, introducing the basics of the concept and why it may be needed. For example:

 * TypeScript does support native string methods, but only types them as `string`
 * Sometimes it's useful to type strings more specifically using string literals. For example ... (include some examples of doing this that don't even use string transformations) - good stuff in https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html
 * Sometimes it can be frustrating when you are using string literals as types, but then you lose that specificity as soon as you need to do a string transformation
 * That's the problem this library solves! (include several typed examples with the "before" and "after")
 * Addendum - why not modify TypeScript to type native string methods the same way this library does? We can't do that because .... but if someone did that this library would become obsolete.
 
That sort of README I think would clarify a lot of questions that people may have when they discover the library for the first time. Thanks!

**Comment by curran** [comment]
This is a great quote for the README from @jly36963 :

>this library preserves literals (and unions of literals) after transformations, unlike most libraries

When I read this line I finally understood the point of the library.

**Comment by gustavoguichard** [comment]
I think I'm also gonna post this screenshot to help people understanding it on first look:
![Screenshot 2023-10-03 at 09 48 13](https://github.com/gustavoguichard/string-ts/assets/566971/128f7dde-587d-4029-9760-3690667a5e4e)

Do you think that would help improving the first impression, @curran ?

**Comment by curran** [comment]
For sure! It's sort of a special case though, for keys. But yes in general screenshots like that would help a lot.

**Comment by gustavoguichard** [comment]
@curran , the PR to clarify the README was merged and I also added a GIF image to create a better first impression.

Would you feel like closing the issue now?

**Comment by curran** [comment]
Very nice!

**Comment by gustavoguichard** [comment]
I appreciate your contribution @curran
