### ISSUE TITLE
Dedent

### ISSUE THREAD

**Issue by BLamy** [gustavoguichard/string-ts#14]
Would be cool to see a typesafe dedent function for template strings. 

This was the closest I got a few months ago. 
https://gist.github.com/BLamy/4b4c369ab4a0915bf61f99e46516fc86

**Comment by gustavoguichard** [comment]
Hey @BLamy , thank you for the suggestion!
I actually didn't even know about dedent.

It would indeed be nice to have it in the library even though I don't think it is a common scenario to have long strings at the type level. For short strings it makes more sense, eg: `type Role = 'admin' | 'editor' | 'user'`

That said if anyone is feeling adventurous and wants to take a shot I'd be curious to see a PR.

**Comment by BLamy** [comment]
I use long string literals in my prompt-builder library pretty extensively. 
https://blamy.gitbook.io/prompt-builder/promptbuilder


<img width="749" alt="image" src="https://github.com/gustavoguichard/string-ts/assets/324928/0e2aa056-9086-46bb-97c6-c540b5e18bbb">

**Comment by gustavoguichard** [comment]
Good to know @BLamy . @jly36963 told me he will take a shot at it.

**Comment by gustavoguichard** [comment]
I'm gonna close this issue as it is just a feature request and it is currently in our [roadmap](https://github.com/gustavoguichard/string-ts/discussions/36).

Make sure you participate in the discussion if you want to see it implemented soon ;)
