### ISSUE TITLE
Wrong npm-packages' github page

### ISSUE THREAD

**Issue by Senbonzakura1234** [gustavoguichard/string-ts#15]
Access package's npm page https://www.npmjs.com/package/string-ts, check repository link

expected behavior: the link should be https://github.com/gustavoguichard/string-ts and the author should be gustavoguichard 

actual behavior: the link currently is https://github.com/gugaguichard/string-ts and the author is gugaguichard

**Comment by gustavoguichard** [comment]
Thank you for reporting @Senbonzakura1234 !
We had a PR sent for that #12 and should be fixed in the next release =)

**Comment by gustavoguichard** [comment]
Fixed in v1.0.0
Thanks for reporting!
