### ISSUE TITLE
Currying (?) for nested keys of objects 

### ISSUE THREAD

**Issue by Joxter** [gustavoguichard/string-ts#19]
Hi, thank you for the lib.

I'm looking for one feature. I don't know how to title it properly, It should work like this:

```
const translations = {a: {b: {c: {d: 'boo'}}}}

const abTranslations = getTranslations(translations, 'a.b');

abTranslations('c.d') // Ok
abTranslations('c.wrong') // Error
```

Could you add this? I even don't know how to google that

**Comment by gustavoguichard** [comment]
Hi @Joxter ! The thing you want I'd probably call a `get` (or `getByPath`) function which is equivalent to [lodash's get](https://lodash.com/docs/4.17.15#get).

It is beyond the scope of this library as it is not related to string but with objects/arrays.

I'll leave you with an implementation though: https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwHMQMAeAFQBp4BleEADwxFWAGd5WMYtUCA+ABQAoeKPg4ARgCsAXPEoixABygYAFnOqKAlJrqNmbeAHJj8APzw0oRDxDB4cgErhkMVlgBuIAOLFyVAAKsKwgweok1Hx8ANxCQhgAnkoIwe5hqmokKupUOMgYSgX6TCzsUKiJANoAuvAAvPC1VGBqaADWJYbsnNy8DSbGfEKNOWpdZfAABgAkAN48iCAwSFjuGAC+84vL8HCcG1NClrbrE0bGAHRmAD4mVbcmNcaKlmmh4Vn7GC1tqJ0MUoXMyWfKFYpyKqXaFgoo-eCtDo1KimYaiOTvDIRb55ApwqizOaI-5bOanA5TYZyYkAgyTUwWcR4iFNaGXWEFX5I+JJFLwFxgNwebx+UgAeSoAGkQIl2IDuvAKtUamiBtLZed2FUditJVQ2Tq9iBODVXvBJZr4O0ZThEPAxYpRJYBUKvL5-GKqpLkUbOKr0VYWCBbKh7Io5A74qBILAEGA8JxxNI5HNFSn4BJ02A5KhkABbCS7DbwYsbOLx1CJ-YDIgYASSKRUABEUEuEkuYCb2jiAHoe2J4AA9czxIQVqvGgBMNeI9ekzdb7eAXaEfYHw6EQA


I hope it helps =)

**Comment by Joxter** [comment]
much appreciated, you helped me a lot even it was beyond the the scope of this library ❤️ 
many thanks!
