### ISSUE TITLE
`join` not functioning correctly

### ISSUE THREAD

**Issue by danharten-sovtech** [gustavoguichard/string-ts#33]
`declare function join<const T extends readonly string[], D extends string = ''>(tuple: T, delimiter?: D): Join<T, D>;`

There are errors on this type in the source code, not sure how to fix though!

**Comment by gustavoguichard** [comment]
Hi @danharten-sovtech , thanks for reporting! What is your TS version?

**Comment by danharten-sovtech** [comment]
Oops, good information to include lol, I am actually using 4.9.5 @gustavoguichard :)

**Comment by gustavoguichard** [comment]
@danharten-sovtech I just checked and removing the const type parameter would make us have to use `as const` every time we'd use `join` like so:

```ts
import { join } from 'string-ts'

const result = join(['hello', 'world'] as const, ' ')
```

That would cause a breaking change so we will only support TS 5+ versions.
We'll make it clear in the documentation.

**Comment by danharten-sovtech** [comment]
I'd say that's a fair outcome, thank you for the efforts @gustavoguichard. Will trial TS 5+ to see if it works for my proj!

**Comment by gustavoguichard** [comment]
You're welcome @danharten-sovtech !
If you can upgrade your TS version you are only gonna benefit from it in many aspects ;)
