### ISSUE TITLE
`toTitleCase` is removing full stops `.`

### ISSUE THREAD

**Issue by danharten-sovtech** [gustavoguichard/string-ts#35]
`console.log(toTitleCase('hello there old friend...'))`

<img width="158" alt="Screenshot 2023-10-05 at 10 39 15" src="https://github.com/gustavoguichard/string-ts/assets/93650937/7f3d2929-95ec-4d3e-ab82-ad7755b4b51f">

Maybe intentional? Not sure :)

**Comment by danharten-sovtech** [comment]
Same log with `console.log(toTitleCase('hello. there. old. friend...'))`

**Comment by gustavoguichard** [comment]
Hi @danharten-sovtech , thanks for reporting.

This is actually how lodash works as well:
<img width="405" alt="Screenshot 2023-10-05 at 07 33 30" src="https://github.com/gustavoguichard/string-ts/assets/566971/6e2dcfc0-5a53-44af-a198-78d87ccbdbee">

The goal of this library is not to be equivalent to lodash but in this case it is.
The casing functions all have the same foundation which is the `words` function that detects words and `join`s them with a different casing. If you think about `toTitleCase` as being from the same family as `toCamelCase` it becomes clearer:
```ts
toTitleCase('hello there old friend...')
// expected to be:
'helloThereOldFriend'

// this would be weird
'helloThereOldFriend...'
```

But as I think about it I realized we should probably have a different naming convention for `toLowerCase` and `toUpperCase` that have a different foundation therefore will keep the dots.

@jly36963 , @p9f , what do you guys think about it?

**Comment by jly36963** [comment]
I would expect all punctuation to be removed
Eg:
```js
toTitleCase('my-kebab-case') // 'My Kebab Case'
toTitleCase('my_snake_case') // 'My Snake Case'
toTitleCase('my.path.case') // 'My Path Case'
```

However, I definitely think we could include specific examples in the documentation to make this clear. As a user, I could see myself be surprised by this behavior as well.

**Comment by jly36963** [comment]
After trying a few different inputs, I do see this though:

```ts
const result = toTitleCase('my.path.case[0]'); // My Path Case [ 0 ]
console.log(result);

/*
// lodash example
_.startCase('my.path.case[0]') // "My Path Case 0"
*/
```

In this case, I would also expect `[` and `]` to be removed (as lodash does).

**Comment by gustavoguichard** [comment]
> /*
> // lodash example
> _.startCase('my.path.case[0]') // "My Path Case 0"
> */

Even though the goal is not to have the same behavior as lodash I agree we should fix this... could you create another issue for it?

As for this issue, let's make it clearer in the docs. Let's check out what lodash does since we are talking about it:
```md
## lowerCase
Converts string, as space separated words, to lower case.

## toLower
Converts string, as a whole, to lower case just like [String#toLowerCase](https://mdn.io/toLowerCase).
```

I thing we should name the methods differently for v2, and implement `lowerCase` and `upperCase`, like they do... for now we can have a different section in the README

**Comment by gustavoguichard** [comment]
@jly36963 maybe we should add `'(' | ')' | '[' | ']' | '{' | '}' | '|'` to [separators](https://github.com/gustavoguichard/string-ts/blob/main/src/utils.ts#L4) and also [here](https://github.com/gustavoguichard/string-ts/blob/main/src/utils.ts#L127).

That should make our library a lil more similar to what people are used to.

**Comment by danharten-sovtech** [comment]
Wow, clocked off for the day to come back to a totally explained and resolved issue. Thank you @gustavoguichard @jly36963!
