### ISSUE TITLE
`endsWith`, `startsWith`, `padStart`, `padEnd`, `includes`, `repeat`, are documented in the README, but missing from exports

### ISSUE THREAD

**Issue by nahoc10** [gustavoguichard/string-ts#46]
`Module '"string-ts"' has no exported member 'endsWith'.ts`

**Comment by gustavoguichard** [comment]
Hey @nahoc10 ! Thanks for reporting!
We did merge all these methods to `main` branch but have not published the package yet.
It will be published in couple hours though and I'll let you know ;)

**Comment by gustavoguichard** [comment]
For now: Relate to [this v1.1 README](https://github.com/gustavoguichard/string-ts/blob/v1.1.0/README.md)

**Comment by gustavoguichard** [comment]
Published: https://github.com/gustavoguichard/string-ts/releases/tag/v1.2.0
