### ISSUE TITLE
Lol

### ISSUE THREAD

**Issue by ArthurKa** [gustavoguichard/string-ts#79]
[▶️ Playground](https://www.typescriptlang.org/play?noImplicitReturns=false&noUncheckedIndexedAccess=true&jsx=0&module=1&ts=5.2.2#code/JYWwDg9gTgLgBAbzgUwHYBMDOB1YMAWcAvnAGZQQhwDkmMUwqA5gLQybUCwAUDwMYRUdOFGSYArgBsYARjgBeFBhx58ACmoBDAEZ9qAGhp6AlDwD0ZuFbgA9APw9+g4aInSATAqVZcBDTr04TUw4OgZmQ2oTc0trex4gA)

![image](https://github.com/gustavoguichard/string-ts/assets/16370704/65b93b0f-2266-488f-bc58-0e3b552dd9d3)

[▶️ Playground](https://www.typescriptlang.org/play?noImplicitReturns=false&noUncheckedIndexedAccess=true&jsx=0&module=1&ts=5.2.2#code/JYWwDg9gTgLgBAbzgGwKYDsDmMAWcC+cAZlBCHAOQDOMUwWAtDFRQLABQHAxhOjXDShwAvJRypkyCBTgBDKgNr1M3XvyioqAV2TxRaLLgAUggJQcA9Bbg24APQD8HIA)

![chrome_c1c0R2WimE](https://github.com/gustavoguichard/string-ts/assets/16370704/3e6d46f2-cd91-471a-8ec6-edcdafd9a8ec)

**Comment by gustavoguichard** [comment]
Hi @ArthurKa !
Thanks for reporting, however I don't get what you mean based on the title of the issue and the fact that you are making an explicit effort to deceive TS by casting to string. The goal of this library is to work with string literals.
What you'd expect?

**Comment by ArthurKa** [comment]
😂😂😂
