### ISSUE TITLE
'"string-ts"' has no exported member named 'trim'. Did you mean 'Trim'?

### ISSUE THREAD

**Issue by adhamfarrag** [gustavoguichard/string-ts#81]
Hi @gustavoguichard, very grateful for your work here. Keep up all this amazing work! 

Upgrading to 1.3.0 is giving me this error `'"string-ts"' has no exported member named 'trim'. Did you mean 'Trim'?ts(2724)
` . Downgrading to 1.2.0 made it work fine.

**Comment by gustavoguichard** [comment]
Hi @adhamfarrag , thanks for reporting!
It should now be fixed in `string-ts@1.3.1` =)
