### ISSUE TITLE
`camelCase` has a weird result on unions

### ISSUE THREAD

**Issue by gustavoguichard** [gustavoguichard/string-ts#9]
`CamelCase<'My Test' | 'Other Test'>` is resulting in `"oyTest" | "otherTest" | "myTest" | "mtherTest"` instead of `'myTest' | 'otherTest'`.
We should investigate why is it happening.

@jly36963 just pinging you given your recent contribution ;)

**Comment by jly36963** [comment]
@gustavoguichard  I can reproduce, I'll work on a fix
