### ISSUE TITLE
Npm package is missing dist folder in 1.3.1

### ISSUE THREAD

**Issue by dovca** [gustavoguichard/string-ts#94]
The latest release 1.3.1 is broken, no javascript files are included. Was this a mistake?

Symptoms:
Failed to resolve entry for package "string-ts". The package may have incorrect main/module/exports specified in its package.json.

**Comment by gustavoguichard** [comment]
Hi @dovca ,
Thanks for reporting! It was my bad, sorry for that.
We will soon automate releases and it should not happen again.

Fixed in 1.3.2
